#!/bin/bash

case "$(printf "lock\nkill\nzzz\nreboot\nshutdown\nwallpaper" | dmenu -i -c -l 6)" in
        lock) slock ;;
	kill) ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	zzz) slock systemctl suspend -i ;;
	reboot) systemctl reboot -i ;;
	shutdown) sudo systemctl poweroff ;;
	wallpaper) bg-switch ;;
	*) exit 1 ;;
esac
