#!/bin/bash

if [ -f "/etc/debian_version" ]; then

  apt install stow wget sway waybar adduser cmake wl-clipboard\
      cmatrix cowsay fd-find firefox-esr flatpak fonts-font-awesome fzf \
      grep grim hostname htop imv kitty git texlive-full maildir-utils\
      neofetch neovim network-manager pipewire rfkill python3 \
      ripgrep sed slurp sudo swaybg swayidle swaylock syncthing tar \
      tmux unzip wlsunset xwayland zathura zip gnupg2

  # gnu stow
  stow .
  
  # setting wlsunset up
  wlsunset -l 50.8 -L 5.6
  echo "wlsunset set!"


  # AUTO-CPUFREQ!!!
  # building spt from source, rusting up
  # config firefox (export all settings)
  # intellij idea ultimate
  # change keyboard mappings

fi
