#!/bin/bash

if [ -f "/etc/debian_version" ]; then

  apt install sway waybar adduser cmake wl-clipboard\
      cmatrix cowsay fd-find firefox-esr flatpak fonts-font-awesome fzf \
      grep grim hostname htop imv kitty git \
      neofetch neovim network-manager pipewire rfkill python3 \
      ripgrep rubber sed slurp sudo swaybg swayidle swaylock syncthing tar \
      thunar tmux unzip wlsunset xwayland zathura zip 
  
  # setting wlsunset up
  wlsunset -l 50.8 -L 5.6
  echo "wlsunset set!"


  # AUTO-CPUFREQ!!!
  # building spt from source, rusting up
  # config firefox (export all settings)
  # intellij idea ultimate
  # change keyboard mappings
  # transfer files from legion to thinkpad

fi
