# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format="""
$character\
$directory\
$git_branch
"""

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[✗](bold red)"

[directory]
style = "bold cyan"

[git_branch]
format="[git:](blue bold)[\\(](blue bold)[$branch](red bold)[\\)](blue bold) "

[package]
disabled = true

