#!/bin/bash
#

# before you do all this, make sure to first transfer your ~/.gnupg/, .gitconfig, .authinfo.gpg, .ssh (DO THIS ONLY IF YOU CHANGE MACHINES FOR GOOD AND ERASE THE OLD DISK)

# add backports repo?

SCRIPTS=""

if [ -f "/etc/debian_version" ]; then

  apt update
  apt install stow sway xdg-desktop-portal-wlr adduser alsa-utils cmake git systemd-resolved hledger ledger \
      cmatrix cowsay fd-find fonts-font-awesome fzf wl-clipboard \
      grep grim gimp hostname imv kitty git bluez cron curl fonts-font-awesome gcc libnotify-bin \
      rfkill python3 thunderbird gpg-agent imagemagick \
      ripgrep rubber sed slurp sudo swaybg swayidle swaylock syncthing tar libspa-0.2-bluetooth \
      unzip usbutils wlsunset zathura zip libreoffice pipewire wireplumber pavucontrol flatpak \
      -y
curl -sS https://starship.rs/install.sh | sh
  # TO INSTALL:
  # auto-cpufreq, build emacs, ledger, configure syncthing, iwgtk
  read -p "Should I install emacs? [y/n]: "
  if [ "$REPLY" == "y" ]; then
      SCRIPTS+="./emacs-build.sh"
  fi

  read -p "Should I install ollama? [y/n]: "
  if [ "$REPLY" == "y" ]; then
      SCRIPTS+=" ./ollama-install.sh"
  fi

  read -p "Should I setup fonts/syncthing/other utils?"
  if [ "$REPLY" == "y" ]; then
      SCRIPTS+=" ./post-install-setup.sh"
  fi


  for script in $SCRIPTS; do
      echo $script 
  done
fi
