#!/bin/bash
#

# before you do all this, make sure to first transfer your ~/.gnupg/, .gitconfig, .authinfo.gpg, .ssh (DO THIS ONLY IF YOU CHANGE MACHINES FOR GOOD AND ERASE THE OLD DISK)

# add backports repo?

SCRIPTS=""

if [ -f "/etc/debian_version" ]; then

  apt update
  apt install stow sway xdg-desktop-portal-wlr waybar adduser alsa-utils cmake git systemd-resolved ledger \
      cmatrix cowsay fd-find fonts-font-awesome fzf wl-clipboard tofi mako-notifier \
      grep grim hostname imv kitty git bluez cron curl fonts-font-awesome gcc libnotify-bin \
      neofetch neovim iwd rfkill python3 thunderbird gpg-agent imagemagick \
      ripgrep rubber sed slurp sudo swaybg swayidle swaylock syncthing tar libspa-0.2-bluetooth \
      unzip usbutils wlsunset zathura zip texlive-full libreoffice pipewire pavucontrol flatpak \
      -y
  
  # setting wlsunset up
  wlsunset -l 50.8 -L 5.6
  echo "wlsunset set!"

cd && git clone --depth 1 https://github.com/protesilaos/iosevka-comfy
cd iosevka-comfy/ && sudo mv iosevka* /usr/share/fonts && fc-cache

curl -sS https://starship.rs/install.sh | sh
  # TO INSTALL:
  # auto-cpufreq, build emacs, ledger, configure syncthing, iwgtk
  read -p "Should I install emacs? [y/n]: "
  if [ "$REPLY" == "y" ]; then
      SCRIPTS+="./emacs-build.sh"
  fi

  read -p "Should I install ollama? [y/n]: "
  if [ "$REPLY" == "y" ]; then
      SCRIPTS+=" ./ollama-install.sh"
  fi


  for script in $SCRIPTS; do
      echo $script 
  done
fi
